name: push

on:
  - push

jobs:
  test:
    name: test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Start Kafka
        uses: 280780363/kafka-action@v1.0
        with:
          kafka version: "latest"
          zookeeper version: "latest"
          kafka port: 9092
          zookeeper port: 2181
          auto create topic: "true"
      - name: Run Cake script
        uses: cake-build/cake-action@v1
        with:
          script-path: ./build/build.cake
          target: Test
          verbosity: Verbose
          arguments: |
            configuration: Release
            nuget_useinprocessclient: true
            settings_skipverification: true
            settings_skippackageversioncheck: true

  coverage:
    name: coverage
    needs: test
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Run Cake script
        uses: cake-build/cake-action@v1
        with:
          script-path: ./build/build.cake
          target: CalculateCoverage
          verbosity: Verbose
          arguments: |
            configuration: Debug
            nuget_useinprocessclient: true
            settings_skipverification: true
            settings_skippackageversioncheck: true
