name: Push or Pull request
on:
  push:
  
  pull_request:

jobs:
  push:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Install packages
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Start Kafka
        uses: 280780363/kafka-action@v1.0
        with:
          kafka version: "latest"
          zookeeper version: "latest"
          kafka port: 9092
          zookeeper port: 2181
          auto create topic: "true"
          
      - name: Test
        run: dotnet test --no-build